"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {nav,pages,PageKey} from "./siteData";

function Shell({children,home=false}:{children:React.ReactNode,home?:boolean}){
 const [menu,setMenu]=useState(false),[panel,setPanel]=useState<"cart"|"login"|"mood"|null>(null),[loaded,setLoaded]=useState(false),[mood,setMood]=useState("");
 useEffect(()=>{requestAnimationFrame(()=>setLoaded(true));const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);setPanel(null)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 return <div className={home?"site-shell home-shell":"site-shell"}><div className={loaded?"loader done":"loader"}><b>L</b><span>LIGHT IN PROGRESS</span></div>
 <header className="topbar"><Link className="round-logo" href="/"><span>Portfolio—</span><b>L</b></Link><nav>{nav.map(([n,h])=><Link href={h} key={h} aria-label={n}><span className="nav-copy" aria-hidden="true"><span>{n}</span><span>{n}</span></span></Link>)}</nav><div className="utilities"><button onClick={()=>setPanel("cart")}><span>0</span><i>Saved</i></button><button onClick={()=>setPanel("login")}><span>☺</span><i>Hello</i></button><button className="menu-trigger" onClick={()=>setMenu(true)}>Menu</button></div></header>
 {children}
 <div className={menu?"mega-menu show":"mega-menu"} aria-hidden={!menu}><button onClick={()=>setMenu(false)}>CLOSE ×</button><nav>{nav.map(([n,h],i)=><Link href={h} key={h} onClick={()=>setMenu(false)}><small>0{i+1}</small>{n}</Link>)}</nav><p>Designer & Developer<br/>Bangkok · Available worldwide</p></div>
 {panel&&<div className="panel-wrap" onMouseDown={()=>setPanel(null)}><aside onMouseDown={e=>e.stopPropagation()}><button className="panel-close" onClick={()=>setPanel(null)}>CLOSE ×</button>{panel==="cart"?<><span className="micro">YOUR SAVED THINGS</span><h2>Nothing here—yet.</h2><p>Keep exploring. Save the things that make your brain light up.</p><Link className="capsule" href="/work">Go to work ↗</Link></>:panel==="mood"?<><span className="micro">QUICK CHECK-IN</span><h2>What’s your creative energy?</h2><p>Just a playful local prototype. Pick one, then replace the labels with your own.</p><div className="mood-spin-scene" aria-hidden="true"><div className="mood-spinner"><span>PLAY · PAUSE · MAKE · NOTICE · </span><div className="spinner-face"><i/><i/><b/></div></div></div><div className="mood-options">{[["LOW","—"],["SLOW","⌣"],["OKAY","•"],["BRIGHT","⌣"],["BUZZING","⌣"]].map(([label,face])=><button key={label} className={mood===label?"selected":""} onClick={()=>setMood(label)}><span>{face}</span>{label}</button>)}</div>{mood&&<p className="mood-response">Noted: {mood}. Keep making at your own pace.</p>}</>:<><span className="micro">WELCOME, CURIOUS ONE</span><h2>Come on in.</h2><label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="capsule">Log in ↗</button></>}</aside></div>}
 {!home&&<footer><div><b>[NAME]</b><span>Designer & Developer.</span></div><nav><Link href="/about">About</Link><Link href="/work">Selected Work</Link><Link href="/support">Contact</Link><a href="mailto:hello@example.com">Email ↗</a></nav><small>© 2026 · PORTFOLIO</small></footer>}</div>
}

function Ticker({dark=false,text="STAY CURIOUS"}:{dark?:boolean,text?:string}){return <div className={dark?"ticker dark":"ticker"}><div>{Array(12).fill(`✳ ${text} `).join("")}</div></div>}
const cardItems=[
 ["01","MOTION","[A small animation or transition study.]","/stories","card-red"],
 ["02","TYPE","[An experiment with expressive typography.]","/stories","card-yellow"],
 ["03","HOVER","[A playful interaction for mouse and keyboard.]","/stories","card-pink"],
 ["04","LAYOUT","[A responsive composition or grid study.]","/stories","card-blue"],
 ["05","CURSOR","[A pointer, drag, or movement experiment.]","/stories","card-green"],
] as const;
function CardDeck({compact=false}:{compact?:boolean}){const [active,setActive]=useState(0);return <section className={compact?"card-deck compact":"card-deck"}>
 <div className="deck-heading"><span className="micro">PLAYGROUND / EXPERIMENTS</span><h2>Small ideas.<br/>Made interactive.</h2><p>Drag sideways, choose a card, and replace each placeholder with your own experiment.</p></div>
 <div className="deck-stage" aria-label="Interactive prompt cards">{cardItems.map((c,i)=><Link href={c[3]} key={c[0]} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} className={`prompt-card ${c[4]} ${active===i?"active":""}`} style={{"--i":i} as React.CSSProperties}><span>{c[0]} / 05</span><b>{c[1]}</b><p>{c[2]}</p><i>↗</i></Link>)}</div>
 <div className="deck-controls"><button onClick={()=>setActive((active+4)%5)} aria-label="Previous card">←</button><span>0{active+1} / 05</span><button onClick={()=>setActive((active+1)%5)} aria-label="Next card">→</button></div>
 </section>}
function Home(){
 const stage=useRef<HTMLDivElement>(null),drag=useRef({active:false,x:0,left:0});
 const wheel=(e:React.WheelEvent<HTMLDivElement>)=>{if(stage.current)stage.current.scrollLeft+=Math.abs(e.deltaY)>Math.abs(e.deltaX)?e.deltaY:e.deltaX};
 const down=(e:React.PointerEvent<HTMLDivElement>)=>{const el=stage.current;if(!el)return;drag.current={active:true,x:e.clientX,left:el.scrollLeft};el.setPointerCapture(e.pointerId)};
 const move=(e:React.PointerEvent<HTMLDivElement>)=>{if(drag.current.active&&stage.current)stage.current.scrollLeft=drag.current.left-(e.clientX-drag.current.x)};
 const up=()=>{drag.current.active=false};
 return <main ref={stage} className="home-stage" onWheel={wheel} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>
  <section className="portfolio-canvas" aria-label="Portfolio overview">
   <article className="portfolio-card p-intro"><span className="tag">PORTFOLIO</span><h1>[Worakan<br/>Portfolio]</h1><p>Developer · Java · React · Nextjs</p></article>
   <Link href="/about" className="portfolio-card p-about"><span className="tag">ABOUT</span><h2>Welcome to my website click here </h2><span className="card-arrow">↗</span></Link>
   <Link href="/work" className="portfolio-card p-project p-project-one"><div className="project-media media-one"><img src="/og.png" alt="Todo list project preview"/></div><span className="tag">PROJECT 01</span><h2>[Todo list]</h2><p>[Role · Create by Nextjs]</p></Link>
   <Link href="/work" className="portfolio-card p-project p-project-two"><div className="project-media media-two"><img src="/og.png" alt="Cafe Cat project preview"/></div><span className="tag">PROJECT 02</span><h2>[Cafe Cat]</h2><p>[Role · Create by Html]</p><span className="card-arrow">↗</span></Link>
   <Link href="/stories" className="portfolio-card p-note"><span className="tag">PLAYGROUND</span><h2>Motion, interface experiments, and things in progress.</h2></Link>
   <article className="portfolio-card p-contact"><span className="tag">CONTACT</span><h2>Let’s make something useful.</h2><a className="plain-action" href="mailto:hello@example.com">EMAIL ME ↗</a><Link className="plain-action light" href="/work">VIEW WORK ↗</Link></article>
   <div className="drag-hint" aria-hidden="true">SCROLL / DRAG <span>→</span></div>
  </section>
 </main>
}
function RevealWords({children,className=""}:{children:string,className?:string}){
 const ref=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){el.classList.add("is-visible");observer.disconnect()}},{threshold:.22});observer.observe(el);return()=>observer.disconnect()},[]);
 return <h2 ref={ref} className={`reveal-words ${className}`}>{children.split(" ").map((word,i)=><span className="reveal-word" style={{"--word":i} as React.CSSProperties} key={`${word}-${i}`}><i>{word}</i>&nbsp;</span>)}</h2>
}
const aboutCards=[["01","NOTICE","[Short description for this item. Add what you noticed, learned, or changed.]"],["02","QUESTION","[Add the question or challenge behind this part of your practice.]"],["03","MAKE","[Explain what you made, your role, tools, and the result here.]"],["04","SHARE","[Add one useful outcome, reflection, or link for people to explore.]"]] as const;
function PileCards(){const [index,setIndex]=useState(4),[moving,setMoving]=useState(true),[paused,setPaused]=useState(false);useEffect(()=>{if(paused)return;const timer=window.setInterval(()=>setIndex(x=>x+1),3000);return()=>window.clearInterval(timer)},[paused]);const settle=(e:React.TransitionEvent<HTMLDivElement>)=>{if(e.target!==e.currentTarget)return;if(index>=8||index<=0){setMoving(false);setIndex(4);requestAnimationFrame(()=>requestAnimationFrame(()=>setMoving(true)))}};const step=(direction:number)=>{setPaused(true);setIndex(x=>x+direction);window.setTimeout(()=>setPaused(false),1500)};return <section className="about-pile about-work-cards"><div className="pile-copy"><span className="micro">SELECTED PRINCIPLES / 01—04</span><h2>A few things I believe.</h2><p>The cards move automatically. Hover or focus one to open its details.</p></div><div className="about-work-viewport" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}><div className={moving?"work-track":"work-track no-motion"} style={{"--index":index} as React.CSSProperties} onTransitionEnd={settle}>{[...aboutCards,...aboutCards,...aboutCards].map((v,i)=><article key={`${v[0]}-${i}`} tabIndex={0} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)}><span className="tag">ITEM {v[0]}</span><div className={`work-art work-art-${i%4}`}><i/><b/></div><h3 className="card-title-roll"><span>{v[1]}</span><span aria-hidden="true">{v[1]}</span></h3><div className="work-detail"><small>DETAIL / PLACEHOLDER</small><p>{v[2]}</p><em>READ MORE ↗</em></div></article>)}</div></div><div className="pile-arrows"><button onClick={()=>step(-1)} aria-label="Previous card"><span className="button-roll"><i>←</i><i>←</i></span></button><button onClick={()=>step(1)} aria-label="Next card"><span className="button-roll"><i>→</i><i>→</i></span></button></div></section>}
const workCards=[["01","[PROJECT ONE]","UI/UX · DEVELOPMENT","A short overview of the problem, your role, and the outcome."],["02","[PROJECT TWO]","BRANDING · MOTION","Add the key idea and what made this project worth showing."],["03","[PROJECT THREE]","PRODUCT · RESEARCH","Explain the challenge, approach, and one measurable result."],["04","[PROJECT FOUR]","EXPERIMENT · CREATIVE CODE","Use this card for a personal project or playful exploration."]] as const;
function WorkCarousel(){const total=workCards.length,[index,setIndex]=useState(total),[moving,setMoving]=useState(true),[paused,setPaused]=useState(false),timer=useRef<number|undefined>(undefined);useEffect(()=>{if(paused)return;timer.current=window.setInterval(()=>setIndex(x=>x+1),3000);return()=>window.clearInterval(timer.current)},[paused]);const settle=(e:React.TransitionEvent<HTMLDivElement>)=>{if(e.target!==e.currentTarget)return;if(index>=total*2||index<=0){setMoving(false);setIndex(total);requestAnimationFrame(()=>requestAnimationFrame(()=>setMoving(true)))}};const step=(n:number)=>{setPaused(true);setIndex(x=>x+n);window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setPaused(false),1500)};return <section className="work-carousel"><header><span className="micro">SELECTED WORK / 01—04</span><h2>Projects, problems,<br/>and outcomes.</h2><p>[Replace these cards with your strongest work. Keep each summary short and specific.]</p></header><div className="work-viewport" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}><div className={moving?"work-track":"work-track no-motion"} style={{"--index":index} as React.CSSProperties} onTransitionEnd={settle}>{[...workCards,...workCards,...workCards].map((card,i)=><article key={`${card[0]}-${i}`} tabIndex={0} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)}><span className="tag">PROJECT {card[0]}</span><div className={`work-art work-art-${i%4}`}><i/><b/></div><h3>{card[1]}</h3><div className="work-detail"><small>{card[2]}</small><p>{card[3]}</p><em>VIEW CASE STUDY ↗</em></div></article>)}</div></div><div className="pile-arrows"><button onClick={()=>step(-1)} aria-label="Previous project"><span className="button-roll"><i>←</i><i>←</i></span></button><button onClick={()=>step(1)} aria-label="Next project"><span className="button-roll"><i>→</i><i>→</i></span></button></div></section>}
function AboutPage(){return <>
 <section className="about-opening">
  <span className="tag">ABOUT / YOUR STORY</span>
  <h1><span>HELLO,</span><span>I’M</span><span>[NAME].</span></h1>
  <p>[One clear sentence about what you make, who it helps, and why you care.]</p>
  <div className="about-spark" aria-hidden="true">✳</div>
 </section>
 <section className="about-statement"><span className="micro">MY POINT OF VIEW</span><RevealWords>I turn curious ideas into clear, useful and memorable experiences.</RevealWords><p>[Add two or three sentences about your approach. Keep it personal and specific.]</p></section>
 <Ticker text="MAKE IT HUMAN"/>
 <PileCards/>
 <section className="about-profile"><div className="profile-art"><i/><b/><span>YOUR<br/>PHOTO<br/>HERE</span></div><article><span className="micro">A LITTLE MORE PERSONAL</span><RevealWords className="profile-title">A short story is more memorable than a long biography.</RevealWords><p>[Write the moment that led you here, what you are learning now, and what kind of work you want to do next.]</p><Link className="capsule" href="/work">SEE MY WORK ↗</Link></article></section>
 <section className="about-numbers"><span className="micro">A FEW USEFUL NUMBERS</span><div>{[["03+","Years making"],["12","Selected projects"],["∞","Questions left"]].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div></section>
 <section className="end-card about-end"><span className="micro">NEXT</span><RevealWords>Have an idea worth making together?</RevealWords><a className="capsule" href="mailto:hello@example.com">START A CONVERSATION ↗</a></section>
 </>}
function Interior({page}:{page:Exclude<PageKey,"home">}){const p=pages[page];const [slide,setSlide]=useState(0),[answer,setAnswer]=useState("");return <>
 <section className={`page-hero ${p.color}`}><span className="tag">{p.kicker} / {p.index}</span><h1>{p.title}</h1><p>{p.intro}</p><div className="hero-orbit">✳</div></section>
 {page==="about"&&<><section className="editorial"><span className="micro">OUR POINT OF VIEW</span><h2>Attention is a form of care. Good work begins by noticing what everyone else walked past.</h2><p>We choose conversation over performance, curiosity over certainty, and systems that feel human in the hand.</p></section><Ticker text="NOTICE MORE"/><section className="stats"><article><b>12</b><span>open questions at any given time</span></article><article><b>01</b><span>shared table, always ready</span></article><article><b>∞</b><span>ways to begin</span></article></section></>}
 {page==="work"&&<WorkCarousel/>}
 {page==="take-five"&&<section className="five"><div className="five-card"><span>0{slide+1} / 05</span><h2>{["Understand the problem.","Find the useful question.","Explore more than one direction.","Build and test the idea.","Refine what matters."][slide]}</h2><div><button onClick={()=>setSlide((slide+4)%5)}>←</button><button onClick={()=>setSlide((slide+1)%5)}>→</button></div></div><aside><b>My process.</b><p>[Replace these steps with your real workflow, tools, collaborators, and decision-making process.]</p></aside></section>}
 {page==="stories"&&<><CardDeck compact/><section className="story-wall">{["I stopped waiting for perfect.","We made a table long enough for everyone.","Saying it out loud made it smaller.","A wrong turn became the whole idea."].map((x,i)=><article key={x}><div className={`avatar a${i}`}/><span>STORY 0{i+1}</span><h2>{x}</h2><button>READ STORY ↗</button></article>)}</section></>}
 {page==="partners"&&<section className="partner"><div className="partner-art"><i/><b/></div><article><span className="micro">SOUL PARTNER 01</span><h2>Common Ground Workshop</h2><p>A small fabrication studio that shares our obsession with honest materials, weird prototypes, and generous collaboration.</p><a className="capsule" href="#">Meet the workshop ↗</a></article></section>}
 {page==="support"&&<section className="checkin"><span className="micro">PROJECT ENQUIRY / SAY HELLO</span><h2>What would you like to make together?</h2><div>{["A website","A digital product","An interactive experiment","Something else"].map(x=><button className={answer===x?"selected":""} onClick={()=>setAnswer(x)} key={x}>{x}<span>○</span></button>)}</div>{answer&&<p className="response">Great — “{answer}”. Replace this prototype response with your email or contact form later.</p>}<a className="capsule" href="mailto:hello@example.com">EMAIL ME ↗</a></section>}
 <Ticker dark text="KEEP THE CONVERSATION MOVING"/><section className="end-card"><span className="micro">NEXT</span><h2>One bright thing can lead to another.</h2><Link className="capsule" href="/">Back to the beginning ↗</Link></section>
 </>}
export function SitePage({page}:{page:PageKey}){return <Shell home={page==="home"}>{page==="home"?<Home/>:page==="about"?<AboutPage/>:<Interior page={page}/>}</Shell>}
